# Generated by Django 4.1.4 on 2022-12-12 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('news_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('news_content', models.TextField(blank=True)),
                ('date_published', models.DateField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(blank=True)),
            ],
        ),
    ]
