# Generated by Django 4.1.4 on 2022-12-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_latest',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
