# Generated by Django 4.1.4 on 2022-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
