# Generated by Django 4.1.4 on 2023-01-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='is_part_of_team',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
