# Generated by Django 4.1.4 on 2022-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='food_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='is_special_menu',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='food_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='is_special_menu',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='food_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='is_published',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='is_special_menu',
            field=models.BooleanField(blank=True),
        ),
    ]
