# Generated by Django 4.1.4 on 2022-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_breakfast_food_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='new_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='old_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='new_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='old_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='new_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='old_price',
            field=models.IntegerField(blank=True),
        ),
    ]
