# Generated by Django 4.1.4 on 2022-12-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_breakfast_new_price_alter_breakfast_old_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='new_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='old_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='new_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='old_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='new_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='old_price',
            field=models.FloatField(blank=True),
        ),
    ]
