# Generated by Django 4.1.4 on 2022-12-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_breakfast_new_price_alter_breakfast_old_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakfast',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='dinner',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='lunch',
            old_name='new_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='breakfast',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='old_price',
        ),
    ]
